# PYTORCH study

## Day 1
***
|구성|내용|
|:------|---|
|torch|메인 패키지|
|torch.autograd|자동 미분 기능 포함. 각종 미분 관련 함수 클래스 포함.|
|torch.nn|신경망 구축에 필요한 구조 및 레이어 포함.|
|torch.optim|SGD를 중심으로 파라미터 최적화 알고리즘 포함.|
|torch.utils.data|SGD 반복 연산시 사용되는 미니 배치용 유틸리티 포함.|
|torch.onnx|ONNX(Open Neural Network Exchange) 포맷으로 모델 export시 사용. 서로 다른 딥러닝 프레임워크 간에 모델 공유시 사용.|

***

tensor는 Numpy의 ndarray와 거의 같은 API

tensor 생성은 torch.tensor 사용

In [1]:
import numpy as np # numpy package
import torch # pytorch package

In [2]:
np_l = np.array([[1,2], [3,4]])

In [3]:
np_l

array([[1, 2],
       [3, 4]])

In [4]:
tc_l = torch.tensor([[1,2], [3,4]])

In [25]:
tc_l

tensor([[1, 2],
        [3, 4]])

In [6]:
torch.cuda.is_available() # GPU 이용 가능 여부 확인

True

In [8]:
tc_gpu = torch.tensor([[1,2], [3, 4.]], device = 'cuda:0') # GPU에 텐서 생성

In [9]:
tc_gpu

tensor([[1., 2.],
        [3., 4.]], device='cuda:0')

In [10]:
tc_f = torch.tensor([[1,2], [3, 4.]], dtype = torch.float64) # 자료형 지정

In [11]:
tc_f

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [13]:
tc_ar = torch.arange(0, 10) # np.arange()와 동일

In [14]:
tc_ar

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
tc_z = torch.zeros(100, 10).to('cuda:0') # 값이 0으로 채워진 100 * 10 배열 GPU에 전송

In [17]:
tc_z[:10] # 10행까지만 출력

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], device='cuda:0')

In [20]:
tc_ran = torch.randn(100, 10) # 정규난수로 100 * 10 배열 생성

In [21]:
tc_ran[:10]

tensor([[ 1.3089, -0.9232,  0.0499,  0.4968,  1.0357, -2.0492,  0.2094, -1.5080,
         -0.8312, -0.3988],
        [ 0.1356, -1.9999, -1.3101, -0.9947, -0.6762, -0.3022, -1.3656, -0.0146,
          0.0469,  0.3259],
        [-0.5867, -0.3053,  2.0828,  0.7191,  0.1888,  1.3761, -1.3774, -0.5773,
          1.0525,  0.1833],
        [-0.8977, -0.3285, -0.6132, -0.9719,  0.5990, -1.0191, -1.8673, -1.9429,
          0.8275,  0.2952],
        [ 0.4623, -0.1626, -0.5590, -0.5964,  0.9415, -0.3166,  0.0612, -0.5731,
          0.3494, -0.5989],
        [ 0.3992,  0.0066, -0.8492,  1.3680,  0.9412,  0.1663, -1.6156, -0.3364,
         -0.9738, -0.2282],
        [ 0.7695, -0.5151, -0.7486, -0.9052,  0.6305,  1.1842,  0.7485,  0.8751,
         -1.3392, -2.1305],
        [ 0.5271, -1.8403,  1.1325, -0.4118, -1.7705, -0.6778, -0.3203, -0.9452,
          0.8203,  0.3896],
        [ 0.8437, -0.1310,  0.2944, -0.2411,  0.1677,  1.0636, -1.0134,  0.6796,
         -0.8362,  0.4575],
        [-0.1944, -

In [22]:
tc_ran.size()

torch.Size([100, 10])

***
GPU의 tensor를 Numpy 형태로 변환할 때 CPU로 먼저 이동 후 변환해야한다.

In [26]:
x = tc_l.numpy() # tensor numpy array로 변환

In [27]:
x

array([[1, 2],
       [3, 4]])

In [30]:
tc_gpu.to('cpu').numpy() # GPU tensor는 CPU로 바꾼 후 numpy 변환 필요

array([[1., 2.],
       [3., 4.]], dtype=float32)

***
tensor의 indexing 및 slicing은 기존 list 형태나 array형태와 동일

In [31]:
tc_l = torch.tensor([[1,2,3], [4,5,6]])

In [32]:
tc_l

tensor([[1, 2, 3],
        [4, 5, 6]])

In [33]:
tc_l[0, 2] # 1(0 + 1)번째 행 3(2 + 1)번째 열 값

tensor(3)

In [36]:
tc_l[:, :2] # 모든행 2번째 열 값까지 출력

tensor([[1, 2],
        [4, 5]])

In [39]:
tc_l[:, [1,2]]

tensor([[2, 3],
        [5, 6]])

In [40]:
tc_l[0, 1] = 100
tc_l

tensor([[  1, 100,   3],
        [  4,   5,   6]])

In [41]:
tc_l[tc_l > 3] = 77
tc_l

tensor([[ 1, 77,  3],
        [77, 77, 77]])

***
tensor 연산은 사칙연산부터 선형 대수 계산까지 가능.

In [48]:
tc_1 = torch.tensor([1, 2, 3.])
tc_2 = torch.tensor([0,10, 20.], dtype = torch.int64)
tc_3 = torch.tensor([[0,1,2], [100,200,300.]])

In [50]:
print(tc_1 + 10)
print(tc_2 ** 2)
print(tc_2 - tc_1)

tensor([11., 12., 13.])
tensor([  0, 100, 400])
tensor([-1.,  8., 17.])


In [52]:
print(tc_3 * 20)
print(tc_1 + tc_3)

tensor([[   0.,   20.,   40.],
        [2000., 4000., 6000.]])
tensor([[  1.,   3.,   5.],
        [101., 202., 303.]])


In [56]:
X = tc_ran * 2 + torch.abs(tc_ran)
X[:5]

tensor([[ 3.9267, -0.9232,  0.1498,  1.4904,  3.1072, -2.0492,  0.6283, -1.5080,
         -0.8312, -0.3988],
        [ 0.4069, -1.9999, -1.3101, -0.9947, -0.6762, -0.3022, -1.3656, -0.0146,
          0.1407,  0.9777],
        [-0.5867, -0.3053,  6.2484,  2.1574,  0.5663,  4.1282, -1.3774, -0.5773,
          3.1574,  0.5499],
        [-0.8977, -0.3285, -0.6132, -0.9719,  1.7969, -1.0191, -1.8673, -1.9429,
          2.4826,  0.8856],
        [ 1.3868, -0.1626, -0.5590, -0.5964,  2.8246, -0.3166,  0.1837, -0.5731,
          1.0482, -0.5989]])

In [59]:
print(X.mean())
print(torch.mean(X))

tensor(0.7359)
tensor(0.7359)


In [60]:
X.mean().item() # 값만 추출

0.7358914017677307

In [64]:
X.mean(0) # 열별 평균

tensor([0.5051, 0.7563, 0.9341, 0.7853, 0.8317, 0.7374, 0.6522, 0.8863, 0.9398,
        0.3307])

tensor의 view는 reshape와 동일한 기능을 한다. 

In [66]:
x1 = torch.tensor([[1,2], [3,4]], dtype = torch.int64)
x2 = torch.tensor([[10, 20, 30], [40, 50, 60.]], dtype = torch.float64)

In [67]:
x1.view(4, 1) # 4행 1열로 변환 / -1 사용하면 한 쪽 알아서 계산 후 변환

tensor([[1],
        [2],
        [3],
        [4]])

In [68]:
x1.view(1, -1) # 1행 4열로 변환

tensor([[1, 2, 3, 4]])

In [70]:
x2.t() # transpose

tensor([[10., 40.],
        [20., 50.],
        [30., 60.]], dtype=torch.float64)

In [71]:
torch.cat([x1, x2], dim = 1)

tensor([[ 1.,  2., 10., 20., 30.],
        [ 3.,  4., 40., 50., 60.]], dtype=torch.float64)

In [93]:
img_tensor = torch.rand(100, 32, 32, 3) # 32 * 32 * 3인 데이터가 100개
img_tensor.transpose(1,2).transpose(1,3).size()

torch.Size([100, 3, 32, 32])

In [100]:
m = torch.randn(20, 10) # 행렬
v = torch.randn(10) # 벡터

d = torch.dot(v, v) # 내적
d

tensor(9.4671)

In [101]:
torch.mv(m, v) # 행렬과 벡터의 곱

tensor([ 2.9409,  0.7851,  0.0155,  1.5257,  1.4310, -1.2635,  6.3545,  1.2938,
        -4.9296,  5.2468, -3.6067, -1.1494,  1.7770,  0.7413, -0.9154,  3.8261,
        -0.8926,  0.3450, -1.0252, -0.4487])

In [103]:
torch.mm(m.t(), m) # 행렬 곱

tensor([[27.0471,  8.6081,  2.6142,  0.2348,  7.7157, -0.7240, -1.7881,  4.4451,
         -4.5580,  3.7338],
        [ 8.6081, 16.5032, -0.1966,  0.1683,  6.3770,  0.9518,  2.7425,  0.5392,
         -0.9085,  2.7103],
        [ 2.6142, -0.1966, 23.4279, -6.0651,  6.2405,  1.5658, -1.6254,  5.4548,
          2.0892, -5.5898],
        [ 0.2348,  0.1683, -6.0651, 15.1189, -5.3497, -4.1648,  6.3950, -4.7703,
         -5.3886,  0.4780],
        [ 7.7157,  6.3770,  6.2405, -5.3497, 20.0031, -0.3860, -6.3713,  0.2271,
          2.7640,  2.6119],
        [-0.7240,  0.9518,  1.5658, -4.1648, -0.3860,  7.2899,  0.7893, -0.6381,
          3.3449, -3.4670],
        [-1.7881,  2.7425, -1.6254,  6.3950, -6.3713,  0.7893, 23.5442, -1.4509,
         -3.2333,  2.5544],
        [ 4.4451,  0.5392,  5.4548, -4.7703,  0.2271, -0.6381, -1.4509, 19.2041,
         -3.4081,  4.4419],
        [-4.5580, -0.9085,  2.0892, -5.3886,  2.7640,  3.3449, -3.2333, -3.4081,
         15.1058, -2.9565],
        [ 3.7338,  

In [109]:
u, s, v = torch.svd(m) # 행렬 분해

***
tensor에는 requires_grad를 이용해 자동 미분 기능 사용 여부를 입력한다.

이후 backward 메서드를 호출하면 자동으로 미분을 계산한다.

In [113]:
x1 = torch.randn(100, 3)
x2 = torch.tensor([1, 2, 3.], requires_grad = True)

In [116]:
y = torch.mv(x1, x2)
s_y = y.sum()

In [117]:
y

tensor([ 3.9642, -4.1987, -4.7638,  2.5454, -3.8672,  3.9084, -0.0680, -0.7424,
         1.8218,  1.4514,  1.7214, -2.9411,  6.0492, -2.7355,  5.2695,  1.6159,
         2.1283,  6.5915,  4.5397,  8.0600,  4.2137,  9.0954, -7.4895,  4.3926,
        -5.6574,  5.8272,  7.7050,  6.5945,  1.9950,  2.7450,  2.5758,  1.6102,
         1.6474, -6.0080,  1.4660,  9.2268, -3.3419,  5.5883,  0.9395, -3.3166,
         4.8400,  3.1532,  0.2063, -0.5223,  3.8702,  1.7911,  5.5306,  1.8818,
        -2.6588,  1.3659,  0.0477,  5.4155, -3.6297, -4.1100, -4.6429, -0.3976,
         2.3137,  6.9941, -2.9570, -6.0408, -0.7523,  0.0169, -0.6234,  5.0016,
         0.2004, -1.3013, -4.2975,  0.0642, -2.2947,  0.2183, -1.4997,  8.8512,
        -0.4532, -0.2805, -2.8990,  3.9734,  2.5361,  1.6934, -1.5985,  0.1825,
         1.3295,  1.9708, -1.2688,  0.2641, -4.2270,  3.2330, -3.6536, -0.7216,
        -1.5129,  5.7481,  0.7008, -3.8626, -1.4494,  1.6729, -1.9030, -4.1510,
        -2.4090, -3.2559, -4.4722,  3.13

In [118]:
s_y

tensor(74.5138, grad_fn=<SumBackward0>)

In [119]:
s_y.backward()

In [120]:
x2.grad != x1.sum(0)

tensor([True, True, True])

In [121]:
x1.grad is None # requires가 False이므로 자동 미분 계산 x

True