## ML 실전


In [58]:
import torch
import torch.nn as nn

import warnings
warnings.filterwarnings('ignore')

In [9]:
### 1차 함수(선형)

layer = nn.Linear(2, 3) # 입력 2, 출력 3

In [10]:
layer

Linear(in_features=2, out_features=3, bias=True)

named_parameters라는 함수를 통해 레이어의 파라미터를 확인할 수 있다.

In [11]:
for param in layer.named_parameters() :
    
    print(f"name : {param[0]}")
    print(f"tensor : {param[1]}")
    print(f"shape : {param[1].shape}")

name : weight
tensor : Parameter containing:
tensor([[-0.1910, -0.6510],
        [ 0.6682,  0.1615],
        [-0.5586,  0.3934]], requires_grad=True)
shape : torch.Size([3, 2])
name : bias
tensor : Parameter containing:
tensor([-0.1285, -0.6623, -0.3237], requires_grad=True)
shape : torch.Size([3])


레이어 함수 안의 파라미터들은 학습의 대상이다.

명시적으로 파라미터 값을 임의로 설정하고 싶은 경우 nn.init.constant_를 호출한다.

In [14]:
nn.init.constant_(layer.weight, 2)

Parameter containing:
tensor([[2., 2.],
        [2., 2.],
        [2., 2.]], requires_grad=True)

In [15]:
nn.init.constant_(layer.bias, 7)

Parameter containing:
tensor([7., 7., 7.], requires_grad=True)

***

### Input 1 Ouput 1

In [16]:
import numpy as np

In [18]:
X = np.arange(-2, 2, 1)

In [20]:
X = torch.Tensor(X).float()

In [23]:
X = X.view(-1, 1)

In [24]:
X

tensor([[-2.],
        [-1.],
        [ 0.],
        [ 1.]])

In [25]:
layer = nn.Linear(1, 1)

In [28]:
nn.init.constant_(layer.weight, 2)

Parameter containing:
tensor([[2.]], requires_grad=True)

In [29]:
nn.init.constant_(layer.bias, 7)

Parameter containing:
tensor([7.], requires_grad=True)

위의 weight, bias를 각각 2, 7로 설정했기 때문에 Linear 식은 $$y = 2x + 7$$

In [30]:
y = layer(X)

In [31]:
y

tensor([[3.],
        [5.],
        [7.],
        [9.]], grad_fn=<AddmmBackward>)

***
### Input 2 Output 1

In [34]:
layer = nn.Linear(2, 1)

In [35]:
print(nn.init.constant_(layer.weight, 1))
print(nn.init.constant_(layer.bias, 2))

Parameter containing:
tensor([[1., 1.]], requires_grad=True)
Parameter containing:
tensor([2.], requires_grad=True)


$$y = x_{1} + x_{2} + 2$$

In [36]:
X = np.array([[0, 0],
             [1, 1],
             [1, 0],
             [0, 1]
             ])

In [38]:
X = torch.Tensor(X).float()

In [40]:
y = layer(X)

In [41]:
y

tensor([[2.],
        [4.],
        [3.],
        [3.]], grad_fn=<AddmmBackward>)

***
### Input 2 Output 3

In [52]:
layer = nn.Linear(2, 3)

In [53]:
layer.weight

Parameter containing:
tensor([[ 0.2044,  0.0722],
        [ 0.1444, -0.5376],
        [ 0.3626, -0.5427]], requires_grad=True)

In [59]:
nn.init.constant(layer.weight[0, :], 1)

tensor([1., 1.], grad_fn=<AsStridedBackward>)

In [60]:
nn.init.constant(layer.weight[1, :], 2)

tensor([2., 2.], grad_fn=<AsStridedBackward>)

In [61]:
nn.init.constant(layer.weight[2, :], 3)

tensor([3., 3.], grad_fn=<AsStridedBackward>)

In [63]:
nn.init.constant(layer.bias, 2)

Parameter containing:
tensor([2., 2., 2.], requires_grad=True)

In [62]:
layer.weight

Parameter containing:
tensor([[1., 1.],
        [2., 2.],
        [3., 3.]], requires_grad=True)

In [64]:
y = layer(X)

In [65]:
y

tensor([[2., 2., 2.],
        [4., 6., 8.],
        [3., 4., 5.],
        [3., 4., 5.]], grad_fn=<AddmmBackward>)

***

### class 활용

In [66]:
class Net(nn.Module) :
    
    def __init__(self, n_input, n_output) :
        super().__init__()
        self.layer1 = nn.Linear(n_input, n_output)
        
    def forward(self, x) :
        return x

In [88]:
inputs = torch.ones(100, 1)

In [89]:
n_input = 1
n_output = 1

In [90]:
net = Net(n_input, n_output)

In [91]:
net

Net(
  (layer1): Linear(in_features=1, out_features=1, bias=True)
)

In [92]:
outputs = net(inputs)

***
### MSELoss

In [76]:
criterion = nn.MSELoss()

In [85]:
loss = criterion(outputs, inputs) / 2.0

In [86]:
loss

tensor(2.)

In [93]:
# loss.backward()