# Pytorch 기본 기능
***
### 핵심

#### 텐서
- 0계 텐서 = 스칼라(수치)
- 1계 텐서 = 벡터
- 2계 텐서 = 행렬

#### 함수

- .view() : numpy의 reshape
- .item() : 텐서에서 클래스의 수치 꺼낼 때 사용 -> 스칼라일 때만 사용 가능
- .max() : 최대치 반환
- .numpy() : 텐서를 넘파이 배열 형태로 변환

In [1]:
import torch

In [2]:
a = torch.tensor(1.0).float()

In [4]:
type(a)

torch.Tensor

In [3]:
a

tensor(1.)

In [5]:
a.dtype

torch.float32

주의>

- 텐서 변수 생성시 dtype을 float32로 변환해야 한다. numpy 변수일 때 변환을 하지 않으면 dtype이 float64가 되어 nn.Linear와 같은 부분에서 오류를 발생시킨다.

In [6]:
a.shape

torch.Size([])

0계 텐서이므로 위와 같이 표기

In [7]:
import numpy as np

In [16]:
b = np.array([1., 2., 3., 4., 5.])

In [17]:
b.shape

(5,)

In [18]:
b_t = torch.tensor(b)

In [20]:
b_t.dtype # float으로 변환안하면 float64 형태

torch.float64

In [21]:
b_t = torch.tensor(b).float()

In [22]:
b_t.dtype

torch.float32

In [23]:
b_t.data

tensor([1., 2., 3., 4., 5.])

In [25]:
### 2계 텐서
c = np.array([[1., 2., 3.],
             [4., 5., 6.]])

In [27]:
c.shape

(2, 3)

In [30]:
c.dtype

dtype('float64')

In [28]:
c_t = torch.tensor(c).float()

In [29]:
c_t

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [31]:
c_t.dtype

torch.float32

In [32]:
torch.manual_seed(42)

In [38]:
### 3계 텐서
d = torch.randn((3, 2, 2)).float()

In [39]:
d.dtype

torch.float32

In [40]:
d

tensor([[[ 0.2815,  0.0562],
         [ 0.5227, -0.2384]],

        [[-0.0499,  0.5263],
         [-0.0085,  0.7291]],

        [[ 0.1331,  0.8640],
         [-1.0157, -0.8887]]])

In [41]:
d.shape

torch.Size([3, 2, 2])

In [42]:
e = torch.ones((2, 3, 2, 2))

In [44]:
e.shape

torch.Size([2, 3, 2, 2])

***
Pytorch의 대부분은 float32 형태를 사용하지만 CrossEntropyLoss, NLLoss의 경우는 정수 타입을 사용한다.

In [48]:
a = a.long()

In [49]:
a

tensor(1)

In [50]:
a.dtype

torch.int64


***
View 함수는 numpy의 reshape과 같은 기능을 한다.

In [63]:
d.shape

torch.Size([3, 2, 2])

In [61]:
d.view(3, -1)

tensor([[ 0.2815,  0.0562,  0.5227, -0.2384],
        [-0.0499,  0.5263, -0.0085,  0.7291],
        [ 0.1331,  0.8640, -1.0157, -0.8887]])

In [62]:
d.view(3, -1).shape

torch.Size([3, 4])

***
Item 함수는 클래스에서 수치를 꺼낼 때 사용 -> 0계 텐서 즉, 스칼라일 때만 사용 가능!

In [67]:
a.item()

1

In [70]:
c.item()

ValueError: can only convert an array of size 1 to a Python scalar

스칼라가 아닐 경우 위와 같이 오류가 발생한다.

단, 1계 텐서(벡터)나 2계 텐서(행렬)라도 요소가 한 개 밖에 없는 경우 사용 가능

In [71]:
t = torch.ones(1)

In [73]:
t.item()

1.0

***

Max 함수는 최대치를 반환한다. torch.max()로도 사용 가능

In [75]:
b.max()

5.0

In [78]:
c

array([[1., 2., 3.],
       [4., 5., 6.]])

In [77]:
c.max()

6.0

In [83]:
torch.max(d, 0)

torch.return_types.max(
values=tensor([[0.2815, 0.8640],
        [0.5227, 0.7291]]),
indices=tensor([[0, 2],
        [0, 1]]))

In [101]:
d[:, 0, 0][0]

tensor(0.2815)

In [100]:
d[:, 0, 1][2]

tensor(0.8640)

In [102]:
d[:, 1, 0][0]

tensor(0.5227)

In [104]:
d[:, 1, 1][1]

tensor(0.7291)

***

In [108]:
d.numpy()

array([[[ 0.28151956,  0.05616354],
        [ 0.52271605, -0.23835687]],

       [[-0.04990335,  0.52633697],
        [-0.00849882,  0.7290606 ]],

       [[ 0.13314196,  0.8639777 ],
        [-1.0156747 , -0.8887485 ]]], dtype=float32)